/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.SpinnerNumberModel;
import presenter.PrincipalPresenter;
import presenter.PrincipalPresenterImpl;

/**
 *
 * @author Hugo
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        presenter = new PrincipalPresenterImpl(this);
        initComponents();
        this.getRootPane().setDefaultButton(jButtonAplicar);
        jSpinnerAlfaLog.setModel(new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1));
        jSpinnerAlfaExp.setModel(new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1));
        jSpinnerLandaSig.setModel(new SpinnerNumberModel(1, 0, 40, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFiltros = new javax.swing.ButtonGroup();
        jPanelControles = new javax.swing.JPanel();
        jButtonAplicar = new javax.swing.JButton();
        jRadioButtonNegativo = new javax.swing.JRadioButton();
        jRadioButtonLogaritmico = new javax.swing.JRadioButton();
        jSpinnerAlfaLog = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonSeno = new javax.swing.JRadioButton();
        jRadioButtonCoseno = new javax.swing.JRadioButton();
        jRadioButtonExp = new javax.swing.JRadioButton();
        jSpinnerAlfaExp = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonSigmoide = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerLandaSig = new javax.swing.JSpinner();
        jPanelPrincipal = new javax.swing.JPanel();
        jScrollPaneImage = new javax.swing.JScrollPane();
        jLabelImage = new javax.swing.JLabel();
        jScrollPaneFilter = new javax.swing.JScrollPane();
        jLabelFilter = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemCargarImagen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Filtros aclarado, oscurecimiento y segmentacion.");

        jPanelControles.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        jButtonAplicar.setText("Aplicar");
        jButtonAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarActionPerformed(evt);
            }
        });

        buttonGroupFiltros.add(jRadioButtonNegativo);
        jRadioButtonNegativo.setSelected(true);
        jRadioButtonNegativo.setText("Negativo");
        jRadioButtonNegativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNegativoActionPerformed(evt);
            }
        });

        buttonGroupFiltros.add(jRadioButtonLogaritmico);
        jRadioButtonLogaritmico.setText("Logaritmico");
        jRadioButtonLogaritmico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLogaritmicoActionPerformed(evt);
            }
        });

        jSpinnerAlfaLog.setValue(1);

        jLabel1.setText("alfa");

        buttonGroupFiltros.add(jRadioButtonSeno);
        jRadioButtonSeno.setText("Seno");
        jRadioButtonSeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSenoActionPerformed(evt);
            }
        });

        buttonGroupFiltros.add(jRadioButtonCoseno);
        jRadioButtonCoseno.setText("Coseno");
        jRadioButtonCoseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCosenoActionPerformed(evt);
            }
        });

        buttonGroupFiltros.add(jRadioButtonExp);
        jRadioButtonExp.setText("Exponencial");
        jRadioButtonExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonExpActionPerformed(evt);
            }
        });

        jSpinnerAlfaExp.setValue(1);

        jLabel2.setText("alfa");

        buttonGroupFiltros.add(jRadioButtonSigmoide);
        jRadioButtonSigmoide.setText("Sigmoide");
        jRadioButtonSigmoide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSigmoideActionPerformed(evt);
            }
        });

        jLabel3.setText("landa");

        jSpinnerLandaSig.setValue(1);

        javax.swing.GroupLayout jPanelControlesLayout = new javax.swing.GroupLayout(jPanelControles);
        jPanelControles.setLayout(jPanelControlesLayout);
        jPanelControlesLayout.setHorizontalGroup(
            jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlesLayout.createSequentialGroup()
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAplicar)
                            .addGroup(jPanelControlesLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(3, 3, 3)
                                .addComponent(jSpinnerAlfaLog, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelControlesLayout.createSequentialGroup()
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelControlesLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonNegativo)
                                    .addComponent(jRadioButtonLogaritmico)))
                            .addGroup(jPanelControlesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonSeno)
                                    .addComponent(jRadioButtonCoseno))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
            .addGroup(jPanelControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonExp)
                    .addComponent(jRadioButtonSigmoide))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(jSpinnerAlfaExp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlesLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(jSpinnerLandaSig, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelControlesLayout.setVerticalGroup(
            jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlesLayout.createSequentialGroup()
                .addComponent(jRadioButtonNegativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonLogaritmico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinnerAlfaLog, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonSeno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCoseno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonExp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinnerAlfaExp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonSigmoide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinnerLandaSig, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButtonAplicar)
                .addContainerGap())
        );

        jScrollPaneImage.setViewportView(jLabelImage);

        jScrollPaneFilter.setViewportView(jLabelFilter);

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneImage, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneFilter)
                    .addComponent(jScrollPaneImage))
                .addContainerGap())
        );

        jMenuArchivo.setText("Archivo");

        jMenuItemCargarImagen.setText("Cargar Imagen ...");
        jMenuItemCargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargarImagenActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemCargarImagen);

        jMenuBar1.add(jMenuArchivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargarImagenActionPerformed
        presenter.cargarImagen();
    }//GEN-LAST:event_jMenuItemCargarImagenActionPerformed

    private void jButtonAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicarActionPerformed
        presenter.aplicarFiltro(filtro);
    }//GEN-LAST:event_jButtonAplicarActionPerformed

    private void jRadioButtonNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNegativoActionPerformed
        filtro = PrincipalPresenter.FILTRO_NEGATIVO;
    }//GEN-LAST:event_jRadioButtonNegativoActionPerformed

    private void jRadioButtonLogaritmicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLogaritmicoActionPerformed
        filtro = PrincipalPresenter.FILTRO_LOGARITMICO;
    }//GEN-LAST:event_jRadioButtonLogaritmicoActionPerformed

    private void jRadioButtonSenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSenoActionPerformed
        filtro = PrincipalPresenter.FILTRO_SENO;
    }//GEN-LAST:event_jRadioButtonSenoActionPerformed

    private void jRadioButtonCosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCosenoActionPerformed
        filtro = PrincipalPresenter.FILTRO_COSENO;
    }//GEN-LAST:event_jRadioButtonCosenoActionPerformed

    private void jRadioButtonExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonExpActionPerformed
        filtro = PrincipalPresenter.FILTRO_EXPONENCIAL;
    }//GEN-LAST:event_jRadioButtonExpActionPerformed

    private void jRadioButtonSigmoideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSigmoideActionPerformed
        filtro = PrincipalPresenter.FILTRO_SIGMOIDE;
    }//GEN-LAST:event_jRadioButtonSigmoideActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFiltros;
    public javax.swing.JButton jButtonAplicar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabelFilter;
    public javax.swing.JLabel jLabelImage;
    public javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCargarImagen;
    public javax.swing.JPanel jPanelControles;
    public javax.swing.JPanel jPanelPrincipal;
    public javax.swing.JRadioButton jRadioButtonCoseno;
    public javax.swing.JRadioButton jRadioButtonExp;
    public javax.swing.JRadioButton jRadioButtonLogaritmico;
    public javax.swing.JRadioButton jRadioButtonNegativo;
    public javax.swing.JRadioButton jRadioButtonSeno;
    public javax.swing.JRadioButton jRadioButtonSigmoide;
    private javax.swing.JScrollPane jScrollPaneFilter;
    public javax.swing.JScrollPane jScrollPaneImage;
    public javax.swing.JSpinner jSpinnerAlfaExp;
    public javax.swing.JSpinner jSpinnerAlfaLog;
    public javax.swing.JSpinner jSpinnerLandaSig;
    // End of variables declaration//GEN-END:variables
    
    private PrincipalPresenter presenter;
    private int filtro = PrincipalPresenter.FILTRO_NEGATIVO;
}
